const SERVICEBOOKING='serviceBooking'
const GET_ALL = `${SERVICEBOOKING}/getAll`
const SAVE_GET_ALL = `${SERVICEBOOKING}/saveGetAll`
const GET_ALL_BOOKING = `${SERVICEBOOKING}/getAllBooking`
const SAVE_GET_ALL_BOOKING = `${SERVICEBOOKING}/saveGetAllBooking`
const GET__BOOKING_DETAIL = `${SERVICEBOOKING}/getBookingDtail`
const BOOKING_SUBMIT = `${SERVICEBOOKING}/bookingSubmit`
export {
    GET_ALL,
    SAVE_GET_ALL,
    GET_ALL_BOOKING,
    SAVE_GET_ALL_BOOKING,
    GET__BOOKING_DETAIL,
    BOOKING_SUBMIT
}